name: projeto_cinema
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-397.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
assets:
  - assets/Rectangle_0.png
  - assets/Rectangle_1.png
  - assets/Rectangle_2.png
  - assets/Rectangle_3.png
  - assets/Rectangle_4.png
  - assets/Rectangle_5.png
  uses-material-design: true
